//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    public partial class m_會員_其他單位 :BaseEntityTable {
    public float 流水號 { get; set; }
    public int 分類編號 { get; set; }
    public string 單位名稱 { get; set; }
    public string 姓名 { get; set; }
    public string 職稱 { get; set; }
    public string 性別 { get; set; }
    public string 公司電話 { get; set; }
    public string 住家電話 { get; set; }
    public string 行動電話 { get; set; }
    public string 傳真電話 { get; set; }
    public string Email { get; set; }
    public string 網站 { get; set; }
    public string 區號 { get; set; }
    public string 地址 { get; set; }
    public string 生日 { get; set; }
    public string 備註 { get; set; }
    public Nullable<int> 排序 { get; set; }
    public bool 顯示狀態Flag { get; set; }
    public Nullable<int> 點閱率 { get; set; }
    public Nullable<System.DateTime> 修改日期 { get; set; }
    public string 新增人員 { get; set; }
    public string 修改人員 { get; set; }
    }
}
